/*!
 * SAP UI development toolkit for HTML5 (SAPUI5/OpenUI5)
 * (c) Copyright 2009-2014 SAP SE or an SAP affiliate company. 
 * Licensed under the Apache License, Version 2.0 - see LICENSE.txt.
 */
jQuery.sap.declare("sap.m.SwitchRenderer");sap.m.SwitchRenderer={};sap.m.SwitchRenderer.CSS_CLASS="sapMSwt";
sap.m.SwitchRenderer.render=function(r,s){var S=s.getState(),a=S?s._sOn:s._sOff,t=s.getTooltip_AsString(),e=s.getEnabled(),n=s.getName(),C=sap.m.SwitchRenderer.CSS_CLASS;if(!s.getVisible()){return}r.write('<div');r.addClass(C+"Cont");if(!e){r.addClass(C+"ContDisabled")}r.writeClasses();r.writeStyles();r.writeControlData(s);if(e){r.writeAttribute("tabindex","0")}if(t){r.writeAttributeEscaped("title",t)}r.write("><div");r.writeAttribute("id",s.getId()+"-switch");r.addClass(C);r.addClass(S?C+"On":C+"Off");r.addClass(C+s.getType());if(sap.ui.Device.system.desktop&&e){r.addClass(C+"Hoverable")}if(!e){r.addClass(C+"Disabled")}r.writeClasses();r.write(">");r.write('<div class="'+C+'Inner">');this.renderText(r,s);this.renderHandle(r,s,a);r.write("</div>");r.write("</div>");if(n){this.renderCheckbox(r,s,a)}r.write("</div>")};
sap.m.SwitchRenderer.renderText=function(r,s){var C=sap.m.SwitchRenderer.CSS_CLASS,d=s.getType()==="Default";r.write('<div class="'+C+'Text '+C+'TextOn">');r.write("<span>");if(d){r.writeEscaped(s._sOn)}r.write("</span>");r.write("</div>");r.write('<div class="'+C+'Text '+C+'TextOff">');r.write("<span>");if(d){r.writeEscaped(s._sOff)}r.write("</span>");r.write("</div>")};
sap.m.SwitchRenderer.renderHandle=function(r,s,S){var C=sap.m.SwitchRenderer.CSS_CLASS;r.write("<div");r.writeAttribute("id",s.getId()+"-handle");r.writeAttributeEscaped("data-sap-ui-swt",S);r.addClass(C+"Handle");if(sap.ui.Device.browser.webkit&&Number(sap.ui.Device.browser.webkitVersion).toFixed(2)==="537.35"){r.addClass(C+"WebKit537-35")}r.writeClasses();r.write("></div>")};
sap.m.SwitchRenderer.renderCheckbox=function(r,s,S){r.write('<input type="checkbox"');r.writeAttribute("id",s.getId()+"-input");r.writeAttributeEscaped("name",s.getName());r.writeAttributeEscaped("value",S);if(s.getState()){r.writeAttribute("checked","checked")}if(!s.getEnabled()){r.writeAttribute("disabled","disabled")}r.write(">")};
